### ISSUE TITLE
Error build flag -mod=readonly only valid when using modules

### ISSUE THREAD

**Issue by joosthooz** [stoewer/parquet-cli#11]
I'm getting an error `build flag -mod=readonly only valid when using modules`, could this project be missing a go.mod file?

**Comment by stoewer** [comment]
Thank you for trying the  `parquet-cli`. The project root does contain a go.mod and a go.sum file and the Makefile / make command works in my dev environment without the error you described. The only way I was able to reproduce the above error was by setting `GO111MODULE=off`.

Please consider the following solutions:
* Check whether go modules are disabled by `GO111MODULE=off`
* Download the compiled binaries from the [releases page](https://github.com/stoewer/parquet-cli/releases)
* Temporarily remove the `-mod=readonly` from the [build / test options](https://github.com/stoewer/parquet-cli/blob/main/Makefile#L3)

Without more information it is difficult to debug this issue. If you continue to have this problem please describe the exact command you used, the go version, operating system, and exported environment variables

**Comment by joosthooz** [comment]
Thanks, it seems `GO111MODULE=off` was in my `go env` for some reason... After unsetting it, it works!
